name: LeetCode Sync

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync LeetCode
        uses: joshcai/leetcode-sync@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          leetcode_session: ${{ secrets.LEETCODE_SESSION }}
          csrf_token: ${{ secrets.CSRF_TOKEN }}
