name: LeetCode Sync

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync LeetCode submissions
        uses: joshcai/leetcode-sync@v1   ✅
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          leetcode_session: ${{ secrets.LEETCODE_SESSION }}
          csrf_token: ${{ secrets.CSRF_TOKEN }}
